name: Hello World

# Definerer hvilke hendelser som trigger workflowen.
on:
  push:
    branches:
      - master  # Trigger på push til main-grenen
  pull_request:
    branches:
      - master  # Trigger på pull requests mot main
jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
    - name: Sjekker ut repository
      uses: actions/checkout@v2

    - name: Print Hello World
      run: echo "Hello, World!"
